### ISSUE TITLE
Method to split a MIBItiff into single TIFFs

### ISSUE THREAD

**Issue by mapazarr** [ionpath/mibilib#89]
Currently there are methods to combine single tiffs into a MIBItiff:
 https://github.com/ionpath/mibitracker-client/blob/master/mibidata/combine_tiffs.py
But the opposite is not possible. It would be helpful to have such a method, in order to visualize the channel images with other programs such as:
 - ImageJ: can display multipage tiffs but does not display the channel name, so the visualization is of limited help.
 - rawTherapee: cannot display multipage tiffs.
 - GIMP: same issue as with ImageJ.

**Comment by rfinck** [comment]
@mapazarr The `tiff.write` method has a flag to save as a file of single-page TIFFs: https://ionpath.github.io/mibitracker-client/mibidata.html?highlight=multichannel#mibidata.tiff.write

If using ImageJ we recommend opening with the BioFormats plugin which is available in FIJI and parses the metadata, although agreed that it does not display it in the optimal location.
